const datas = [
  {
    name: 'l\'Eau Tarie',
    location: 'Rues piétonnes',
	locationTag : ['centre-ville', 'rues piétonnes'],
	image : 'http://arthurfortin.fr/images/eauta.jpg',
    page: 'https://www.facebook.com/www.leautarielehavre.fr/?fref=ts',
	typetag : ['bar' ],
	boissonstag : ['mojito', 'bière', 'caïpirihna' ],
	nourrituretag : ['tapas', 'burger' ],
	animationtag : ['danser'],
	musiquetag: ['' ],
	aménagementtag: ['terrasse', 'terrasse chauffée' ],
	ouverturetag : ['dimanche', 'lundi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un rade bien sympa pour manger sans se saigner le midi, et prendre un apéro sans trop se les meuler grâce à la terrasse chauffée.'
  },
  {
    name: 'l\'Abri Côtier',
    location: 'plage',
    page: 'https://www.facebook.com/abricotier/?fref=ts',
	locationTag : ['mer', 'plage'],
	image : 'http://arthurfortin.fr/images/abri.jpg', 
	typetag : ['bar' ],
	boissonstag : ['mojito', 'bière', 'caïpirihna', 'cocktail' ],
	nourrituretag : ['tapas', 'accras', 'foccacias' ],
	animationtag : ['expo', 'exposition'],
	musiquetag: [''],
	aménagementtag: ['terrasse', 'terrasse chauffée' ],
	ouverturetag : ['midi', 'dimanche'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Le meilleur bar du Havre. Un emplacement parfait, une équipe au top et en plus on peut danser jusqu\'à 2h le samedi soir.'
  },
  {
    name: 'Le Trappiste',
    location: 'Niemeyer',
	locationTag : ['centre-ville', 'niemeyer', 'halles'], 
	image : 'http://arthurfortin.fr/images/abri.jpg',
    page: 'https://www.facebook.com/LeTrappistLeHavre/?fref=ts',
	typetag : ['bar' ],
	boissonstag : ['bière', 'bière belge'],
	nourrituretag : ['saucisson'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: ['terrasse', 'terrasse chauffée' ],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un rade bien décoré pour celles et ceux qui aiment la bière qui fait mal aux boulons.'
  },
  {
    name: 'O\'Brother',
    location: 'Niemeyer',
	locationTag : ['centre-ville', 'niemeyer', 'halles'], 
	image : 'http://arthurfortin.fr/images/obr.jpg',
    page: 'https://www.facebook.com/obrotherlh',
	typetag : ['bar' ],
	boissonstag : ['bière'],
	nourrituretag : ['saucisson', 'tapas', 'burger','hamburger'],
	animationtag : ['match', 'rugby', 'foot'],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un bar à l\'ambiance irish idéal pour se mater un match. A noter une bouffe excellente le midi.'
  },
    {
    name: 'L\'Etable',
    location: 'rues Piétonnes',
	locationTag : ['centre-ville', 'rues piétonnes'],
	image : 'http://arthurfortin.fr/images/eta.jpg',
    page: 'https://www.facebook.com/etable76',
	typetag : ['bar' ],
	boissonstag : ['bière', 'vin'],
	nourrituretag : ['tapas', 'chartuerie'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un lieu agréable pour se prendre un coup au calme. '
  },
    
  {
    name: 'La Petite Rade',
    location: 'plage',
	locationTag : ['plage', 'mer'],
	image : 'http://arthurfortin.fr/images/rade.jpg',
    page: 'https://www.facebook.com/La-Petite-Rade-188341881206913',
	typetag : ['bar' ],
	boissonstag : ['bière', 'mojito'],
	nourrituretag : ['burger', 'tapas', 'frites'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : ['dimanche'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'LE spot pour se siffler une mousse en mangeant un burger délicieux.'
  },
  
  {
    name: 'Crêpe Chignon',
    location: 'Saint-François',
	locationTag : ['saint-françois'],
	image : 'http://arthurfortin.fr/images/chign.jpg',
	typetag : ['restaurant', 'resto', 'crêperie' ],
	boissonstag : ['cidre'],
	nourrituretag : ['crêpes'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
    page: 'https://www.facebook.com/La-Petite-Rade-188341881206913',
	avis: '♪ Ils ont des chapeaux ronds, vive la Bretagne... ♪'
  },
  
  {
    name: 'Le Cosmopolite',
    location: 'Saint-Nicolas',
	locationTag : ['saint-nicolas'],
	image : 'http://arthurfortin.fr/images/cosm.jpg',
	typetag : ['boîte de nuit' ],
	boissonstag : ['bière','cocktails'],
	nourrituretag : [''],
	animationtag : ['danser'],
	musiquetag: ['électro', 'mainstream', 'dj'],
	aménagementtag: [''],
	ouverturetag : ['après 2h'],
	livraisontag : [''],
	marquetag : [''],
    page: 'https://www.facebook.com/cosmolh/',
	avis: 'Si tu veux guincher tu peux y faire un tour'
  },
  
   {
    name: 'Le Music Bar',
    location: 'Saint-Nicolas',
	locationTag : ['saint-nicolas'],
	image : 'http://arthurfortin.fr/images/musbar.jpg',
	typetag : ['boîte de nuit' ],
	boissonstag : ['bière','cocktails'],
	nourrituretag : [''],
	animationtag : ['danser', 'karaoké'],
	musiquetag: ['électro', 'mainstream', 'dj'],
	aménagementtag: [''],
	ouverturetag : ['après 2h'],
	livraisontag : [''],
	marquetag : [''],
    page: 'https://www.facebook.com/pages/Music-Bar/158778094180401',
	avis: 'Tu es ivre et tu veux pouvoir t\'exprimer après 2h du matin ? Ce lieu est fait pour toi' 
  },
  
      {
      name: 'le Chat Bleu',
    location: 'Sainte-Adresse',
	locationTag : ['plage', 'mer'],
	image : 'http://arthurfortin.fr/images/chat.jpeg',
	typetag : ['salon de thé', 'brocante', 'restaurant' ],
	boissonstag : ['bière','café', 'thé','vin', 'vin bio' ],
	nourrituretag : ['quiches', 'salades'],
	animationtag : ['expos', 'expositions', 'concerts', 'brunch'],
	musiquetag: ['électro', 'jazz', 'piano'],
	aménagementtag: ['terrasse'],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	page: 'https://www.facebook.com/Le-Chat-Bleu-au-bon-goût-dici-et-dailleurs-294275044012714',
	avis: 'Le refuge idéal pour les urbains souhaitant trouver un refuge où manger un bout, prende un thé ou une mousse. Tout est bon, tout est fait maison.'
  },
  
  {
    name: 'Williamsburg',
    location: 'Rues piétonnes',
	locationTag : ['centre-ville', 'rues piétonnes'],
	image : 'http://arthurfortin.fr/images/will.jpg',
    page: 'https://www.facebook.com/Williamsburg-Food-Coffee-771263892910406',
	typetag : ['coffee shop' ],
	boissonstag : ['café','cappucino', 'chocolat chaud'],
	nourrituretag : ['cheesecake', 'sandwich', 'muffin', 'salade', 'cheesecake'],
	animationtag : ['petit déjeuner', 'goûter'],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Le Havre a son coffee shop, tu peux y aller les yeux fermés.'
  },
  
   {
    name: 'French Coffee Shop',
    location: 'hôtel-de-ville',
	locationTag : ['hôtel-de-ville', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/french.jpg',
    page: 'https://www.facebook.com/LHfrenchcoffeeshop/',
	typetag : ['coffee shop' ],
	boissonstag : ['café','cappucino', 'chocolat chaud'],
	nourrituretag : ['cheesecake', 'sandwich', 'muffin', 'salade', 'cheesecake'],
	animationtag : ['petit déjeuner', 'goûter'],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un chouette coffee shop, à la starbuck style.'
  },
  
   {
    name: 'L\'Escapade',
    location: 'plage',
	locationTag : ['plage', 'mer'],
	image : 'http://arthurfortin.fr/images/esc.jpg',
    page: 'https://www.facebook.com/Lescapade76',
	typetag : ['bar' ],
	boissonstag : ['vin'],
	nourrituretag : ['charcuterie', 'fromage'],
	animationtag : ['dégustations'],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Une cave et un  à vin vraiment sympas avec un petit coin jardin où siroter du bon pinard.'
  },
  
     {
    name: 'Chez André',
    location: 'Bellanger',
	locationTag : ['Bellanger', 'saint-vincent'],
	image : 'http://arthurfortin.fr/images/andre.jpg',
    page: 'https://www.facebook.com/restaurantchezandre/',
	typetag : ['restaurant', 'resto' ],
	boissonstag : ['vin'],
	nourrituretag : ['fromage'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Unun chouette  où siroter du bon pinard.'
  },
  
   {
    name: 'Le Cyclamen',
    location: 'Saint-François',
	locationTag : ['Saint-François', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/cycl.jpg',
    page: 'https://www.facebook.com/pages/Le-Cyclamen/178489788865708',
	typetag : ['bar' ],
	boissonstag : ['cocktails', 'rhum', 'mojito', 'Caïpirinha'],
	nourrituretag : [''],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Une cave et un  à vin vraiment sympas avec un petit coin jardin où siroter du bon pinard.'
  },
    
	{
    name: 'La Cave à bière',
    location: 'saint-vincent',
	locationTag : ['saint-vincent', 'centre-ville'],
    page: 'https://www.facebook.com/AffichesLaCaveABieresLeHavre',
	typetag : ['magasin' ],
	boissonstag : ['bière', 'bière belge'],
	nourrituretag : [''],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Le lieu idéal pour acheter de la bonne bière et savourer une expo.'
  },
  
  {
    name: 'Naturéo',
    location: 'Le Grand Hameau',
	locationTag : ['Grand Hameau', 'ville haute'],
	image : 'http://arthurfortin.fr/images/natur.jpg',
    page: '',
	typetag : ['magasin' , 'bio'],
	boissonstag : [''],
	nourrituretag : [''],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un endroit pour acheter bio avec du choix'
  },
  
    {
    name: 'Rayons Verts',
    location: 'Avenue Coty',
	locationTag : ['avenue coty'],
	image : 'http://arthurfortin.fr/images/ray.jpg',
    page: 'https://www.facebook.com/Rayons-Verts-1421643768155053',
	typetag : ['magasin' , 'bio'],
	boissonstag : [''],
	nourrituretag : [''],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un endroit pour acheter bio avec du choix'
  },
  
   {
    name: 'Le Marché Bio',
    location: 'rue de Paris',
	locationTag : ['centre-ville', 'Notre-Dame'],
	image : 'http://arthurfortin.fr/images/marchbio.jpg',
    page: 'https://www.facebook.com/lemarchebioLH/',
	typetag : ['magasin' , 'bio'],
	boissonstag : [''],
	nourrituretag : [''],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un endroit pour acheter bio avec du choix'
  },
  
  {
    name: 'All in Bagels',
    location: 'Saint-Nicolas et Niemeyer',
	locationTag : ['Saint-Nicolas', 'Niemeyer', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/all.jpg',
    page: 'https://www.facebook.com/AllInBagels',
	typetag : ['fast food' ],
	boissonstag : ['café','cappucino'],
	nourrituretag : ['bagels', 'salade'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['à emporter'],
	marquetag : [''],
	avis: 'Ca tombe bien que tu aimes ça car je vais te dire la meilleure adresse de la ville : All in Bagels'
  },
  
    {
    name: 'Istanbul',
    location: 'saint-vincent',
	locationTag : ['saint-vincent', 'plage'],
	image : 'http://arthurfortin.fr/images/ist.jpg',
    page: 'https://www.facebook.com/pages/Istanbul-Kebab/251742424858786',
	typetag : ['fast food' ],
	boissonstag : [''],
	nourrituretag : ['kebab'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi', 'dimanche'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Le meilleur kebab de France par kebab-frites.com'
  },
  
  {
    name: 'Sushis Makers',
    location: 'Notre-Dame',
	locationTag : ['Notre-dame', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/sush.jpg',
    page: 'https://www.facebook.com/sushimakers',
	typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['japonais', 'sushis'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['livraison', 'livre'],
	marquetag : [''],
	avis: 'Du japonais fait maison. Si si'
  },
  
  {
    name: 'Le Grignot',
    location: 'Niemeyer',
	locationTag : ['centre-ville', 'niemeyer'],
	image : 'http://arthurfortin.fr/images/grign.jpg',
    page: 'https://www.facebook.com/legrignotLH',
	typetag : ['brasserie' ],
	boissonstag : [''],
	nourrituretag : ['fruits de mer', 'fruits de mer', 'entrecôte', 'viande', 'bavette'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Une chouette brasserie à la déco typique'
  },
  
  {
    name: 'Saïgon',
    location: 'saint-vincent',
	locationTag : ['centre-ville', 'saint-vincent'],
	image : 'http://arthurfortin.fr/images/sai.jpg',
    page: 'https://www.petitfute.com/v16634-le-havre-76600/c650-produits-gourmands-vins/c1108-produits-du-monde/421611-saigon.html',
		typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['chinois', 'nems'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['emporter'],
	marquetag : [''],
	avis: 'LE meilleur chinois de la ville'
  },
  
   {
    name: 'Le Palais Impérial',
    location: 'rue Aristide Briant',
	locationTag : ['centre-ville', 'saint-vincent'],
	image : 'http://arthurfortin.fr/images/pal.jpg',
	typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['chinois', 'nems'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['emporter'],
	marquetag : [''],
    page: 'http://www.palais-imperial.fr/',
	avis: 'J\'ai pas test pour être franc mais il est bien noté'
  },
  
   {
    name: 'Al Dente',
    location: 'Niemeyer',
	locationTag : ['Niemeyer', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/ald.jpg',
    page: 'https://www.facebook.com/Al-Dente-Ristorante-196816710348037',
	typetag : ['restaurant', 'pizzeria' ],
	boissonstag : [''],
	nourrituretag : ['pizza', 'italien', 'pâtes'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['emporter'],
	marquetag : [''],
	avis: 'L\'un des meilleurs italiens de la ville, basta !'
  },
  
   {
    name: 'O Délices du Liban',
    location: 'Rue de la Soif',
	locationTag : ['plage'],
	image : 'http://arthurfortin.fr/images/odel.jpg',
    page: 'https://www.facebook.com/odelicesdulibanduhavre',
	typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['libanais', 'mezzé', 'chawerma', 'falafel'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['emporter'],
	marquetag : [''],
	avis: 'Un excellent Libanais'
  },
  
   {
    name: 'Le Fifty\'s',
    location: 'Rue de la Soif',
	locationTag : ['les halles', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/fift.jpg',
	typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['burger'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : ['emporter'],
	marquetag : [''],
    page: 'https://www.facebook.com/odelicesdulibanduhavre',
	avis: 'Un burger comme dans les 50\'s. Sors ton costume champion et fais comme les américains. En plus ils font des apéros avec de vrais assiettes qui te calent. Pas comme ces voleurs qui te mettent 3 trucs à becqueter'
  },
  
  {
    name: 'La Petite Savoie',
    location: 'Saint-François',
	locationTag : ['centre-ville', 'saint-françois'],
	image : 'http://arthurfortin.fr/images/savoi.jpg',
    page: 'https://www.facebook.com/pages/La-Petite-Savoie/156213701077390',
	typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['fromage','raclette'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Si tu veux manger du fromage et avoir une haleine de raclette c\'est là que ça se passe'
  },
    
	  {
    name: 'Le Lyonnais',
    location: 'Saint-François',
	locationTag : ['centre-ville', 'saint-françois'],
	image : 'http://arthurfortin.fr/images/lyo.jpg',
    page: 'https://www.facebook.com/pages/Le-Lyonnais/206566939421182',
	typetag : ['restaurant' ],
	boissonstag : [''],
	nourrituretag : ['escargots'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un excellent resto pour une bonne gastronomie française au sein d\'un environnement chaleureux'
  },
  
    {
    name: 'Taverne Paillette',
    location: 'Saint-Roch',
	locationTag : ['centre-ville', 'saint-roch'],
	image : 'http://arthurfortin.fr/images/pail.jpg',
    page: 'https://www.facebook.com/La-Taverne-Paillette-176529912364014',
	typetag : ['brasserie' ],
	boissonstag : [''],
	nourrituretag : ['moules', 'fruits de mer', 'choucroute'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : ['midi', 'dimanche'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un classique havrais. Si t\'as pas essayé cette brasserie typique t\'as loupé ta vie '
  },
  
   {
    name: 'Le Bureau',
    location: 'Niemeyer',
	locationTag : ['centre-ville', 'niemeyer'],
	image : 'http://arthurfortin.fr/images/bur.jpg',
    page: 'https://www.facebook.com/aubureau.lehavre',
	typetag : ['brasserie', 'bar' ],
	boissonstag : [''],
	nourrituretag : ['fish\'n ships', 'burger', 'hamburger'],
	animationtag : ['concert', 'afterwork'],
	musiquetag: ['rock'],
	aménagementtag: [''],
	ouverturetag : ['midi', 'dimanche'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'L\'un des seuls lieux où manger un fish\'n ships. A 3h de l\'Irlande c\'est à noter'
  },
  
   {
    name: 'Ortiz',
    location: 'Plage',
	locationTag : ['centre-ville', 'plage', 'mer'],
	image : 'http://arthurfortin.fr/images/ortiz.jpg',
    page: 'https://www.facebook.com/aubureau.lehavre',
	typetag : ['glacier'],
	boissonstag : [''],
	nourrituretag : ['glace', 'glace italienne'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'L\'institution glacière au Havre. Idéal pour une glace à la plage'
  },
  
  {
    name: 'Fleur de Sel',
    location: 'Saint-François',
	locationTag : ['centre-ville', 'Saint-François'],
	image : 'http://arthurfortin.fr/images/fleur.jpg',
    page: 'https://www.facebook.com/Fleur-de-Sel-665021900279649',
	typetag : ['restaurant', 'gastronomique'],
	boissonstag : [''],
	nourrituretag : ['truffe', 'poisson'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Raffiné et abordable'
  },
  
    {
    name: 'Tartarin',
    location: 'avenue foch',
	locationTag : ['centre-ville', 'avenue foch'],
	image : 'http://arthurfortin.fr/images/tart.png',
    page: 'https://www.facebook.com/Restaurant-Jean-Luc-Tartarin-146369338737976',
	typetag : ['restaurant', 'gastronomique'],
	boissonstag : [''],
	nourrituretag : ['truffe', 'poisson'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'La crème de la crème'
  },
  
   {
    name: 'Saveurs Île Maurice',
    location: 'quai Southampton',
	locationTag : ['centre-ville', 'quai Southampton'],
	image : 'http://arthurfortin.fr/images/odel.jpg',
    page: 'https://www.facebook.com/Saveurs-Ile-Maurice-282357235180859',
	typetag : ['restaurant'],
	boissonstag : ['pina colada'],
	nourrituretag : ['accras', 'samoussas'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Connais pas mais j\'ai entendu de bonnes choses donc...'
  },
  
    {
    name: 'Louise',
    location: 'rues piétonnes',
	locationTag : ['centre-ville', 'rues piétonnes'],
	image : '',
    page: 'https://www.facebook.com/louise.cafe.le.havre',
	typetag : ['glacier'],
	boissonstag : [''],
	nourrituretag : ['glace', 'glace italienne'],
	animationtag : [''],
	musiquetag: [''],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Pour savourer une bonne glace avec un café'
  },
  
  
      {
    name: 'le Bistrot',
    location: 'avenue Coty',
	locationTag : ['coty'],
	image : 'http://arthurfortin.fr/images/lebis.jpg',
    page: 'https://www.facebook.com/lebistrotcoty',
	typetag : ['bistrot', 'bar'],
	boissonstag : ['bière'],
	nourrituretag : [''],
	animationtag : ['concert'],
	musiquetag: ['rock'],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Une institution qui mérite d\'être redécouverte par les jeunes générations.'
  },
  
  {
    name: 'le Merle Moqueur',
    location: 'notre-dame',
	locationTag : ['notre-dame'],
	image : 'http://arthurfortin.fr/images/merl.jpg',
    page: 'https://www.facebook.com/Le-Merle-Moqueur-383939731755519',
	typetag : ['bistrot', 'bar'],
	boissonstag : ['bière'],
	nourrituretag : [''],
	animationtag : ['concert'],
	musiquetag: ['rock'],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un rade à la bonne franquette comme vous dîtes vous autres les humains'
  },
  
    {
    name: 'Zazous',
    location: 'hôtel-de-ville',
	locationTag : ['hôtel-de-ville'],
	image : 'http://arthurfortin.fr/images/zaz.jpg',
    page: 'https://www.facebook.com/leszazouslehavre',
	typetag : ['bistrot', 'bar'],
	boissonstag : ['bière'],
	nourrituretag : [''],
	animationtag : ['concert', 'blind test'],
	musiquetag: ['rock'],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'bonne ambiance, bon délire et des sessions blind test chaque semaine pour se fendre la poire et écouter des gens mal chanter.'
  },
  
  {
    name: 'Wallaby Bar',
    location: 'hôtel-de-ville',
	locationTag : ['saint-françois'],
	image : 'http://arthurfortin.fr/images/zaz.jpg',
    page: 'https://www.facebook.com/wallaby..7',
	typetag : ['bistrot', 'bar'],
	boissonstag : ['bière', 'mojito'],
	nourrituretag : [''],
	animationtag : ['concert'],
	musiquetag: ['rock'],
	aménagementtag: [''],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un bon rade niché dans Saint-François qui te donne l\'impression de vivre un été permanent'
  },
    
  {
    name: 'Bistrot de Quentin',
    location: 'hôtel-de-ville',
	locationTag : ['saint-françois'],
	image : 'http://arthurfortin.fr/images/quentin.jpg',
    page: 'https://www.facebook.com/lebistrotdequentin',
	typetag : ['bar' ],
	boissonstag : ['bière'],
	nourrituretag : ['saucisson', 'tapas', 'burger','hamburger'],
	animationtag : ['happy hours'],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Un très bon resto le midi et un très bon rade le soir.'
  },
  
   {
    name: 'Black Café',
    location: 'Niemeyer',
	locationTag : ['Niemeyer'],
	image : 'http://arthurfortin.fr/images/bla.jpg',
    page: 'https://www.facebook.com/Black-Café-739396976180251',
	typetag : ['bar' ],
	boissonstag : ['bière'],
	nourrituretag : ['saucisson', 'tapas'],
	animationtag : ['billard', 'fléchettes'],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : ['midi'],
	livraisontag : [''],
	marquetag : [''],
	avis: 'Le spot idéal pour se faire un billard'
  },
  
   {
    name: 'Mac Daid\'s',
    location: 'Niemeyer',
	locationTag : ['Niemeyer', 'centre-ville'],
	image : 'http://arthurfortin.fr/images/mac.jpg',
    page: 'https://www.facebook.com/pages/Mac-Daids/115590181861208',
	typetag : ['bar' ],
	boissonstag : ['bière'],
	nourrituretag : ['saucisson', 'tapas'],
	animationtag : ['billard', 'fléchettes'],
	musiquetag: [''],
	aménagementtag: ['terrasse'],
	ouverturetag : [''],
	livraisontag : [''],
	marquetag : ['guinness'],
	avis: 'LE pub havrais'
  },
    

  
 ]

module.exports = datas
