module.exports = {
getInfoPokemon : require('./infopokemon.js'),
 greetings : require('./greetings.js'),
 merci : require('./merciAnswer.js'),
 aurevoir : require('./byeAnswer.js'),
 cava : require('./cavaAnswer.js'),
 insultes : require('./insultesAnswer.js'),
nom : require('./nomAnswer.js')  ,
createur : require('./createurAnswer.js')  ,
age : require('./ageAnswer.js')  ,
mappelle : require('./mappelleAnswer.js')  ,
findresto : require('./findresto.js')  ,
lol : require('./lolAnswer.js')  ,
emo : require('./emoAnswer.js')  ,
resto: require('./restoAnswer.js')  ,
activiteinfo: require('./activiteAnswer.js')  ,
commoditeinfo: require('./commoditeAnswer.js')  ,
achatinfo: require('./achatAnswer.js')  ,
tagresto: require('./tagAnswer.js')  ,
 } 