module.exports = {
 greetings : require('./greetings.js'),
 merci : require('./merciAnswer.js'),
 aurevoir : require('./byeAnswer.js'),
 cava : require('./cavaAnswer.js'),
 insultes : require('./insultesAnswer.js'),
nom : require('./nomAnswer.js')  ,
createur : require('./createurAnswer.js')  ,
age : require('./ageAnswer.js')  ,
mappelle : require('./mappelleAnswer.js')  ,
illegal : require('./illegalAnswer.js')  ,
findresto : require('./findresto.js')  ,
lol : require('./lolAnswer.js')  ,
emo : require('./emoAnswer.js')  ,
tagresto: require('./tagAnswer.js')  ,
 } 