module.exports = {
getInfoPokemon : require('./infopokemon.js'),
 manger : require('./mangerAnswer.js'),
 promenade : require('./promenadeAnswer.js'),
 greetings : require('./greetings.js'),
 merci : require('./merciAnswer.js'),
 homeapero : require('./homeaperoAnswer.js'),
 sortirAnswer : require('./sortirAnswer.js'),
 vinAnswer : require('./vinAnswer.js'),
 libanaisAnswer : require('./libanaisAnswer.js'),
 the : require('./theAnswer.js'),
 hotelAnswer : require('./hotelAnswer.js'),
 pizzalh : require('./pizzaAnswer.js'),
 boites : require('./boitesAnswer.js'),
 aurevoir : require('./byeAnswer.js'),
 concert : require('./concertAnswer.js'),
 gastro : require('./gastroAnswer.js'),
 cava : require('./cavaAnswer.js'),
 apero : require('./aperoAnswer.js'),
 burger : require('./burgerAnswer.js'),
 moules : require('./mouleAnswer.js'),
 salade : require('./saladeAnswer.js'),
 frites : require('./friteAnswer.js'),
 bouchonsr : require('./bouchonsAnswer.js'),
 biere: require('./biereAnswer.js'),
 sushis : require('./sushisAnswer.js'),
 chinois : require('./chinoisAnswer.js'),
  cafe : require('./cafeAnswer.js'),
 kebab : require('./kebabAnswer.js'),
 insultes : require('./insultesAnswer.js'),
 cocktails : require('./cocktailsAnswer.js'),
 musee : require('./museeAnswer.js')  ,
bagel : require('./bagelAnswer.js')  ,
nom : require('./nomAnswer.js')  ,
petanque : require('./petanqueAnswer.js')  ,
createur : require('./createurAnswer.js')  ,
age : require('./ageAnswer.js')  ,
mappelle : require('./mappelleAnswer.js')  ,
findresto : require('./findresto.js')  ,
crepe : require('./crepeAnswer.js')  ,
illegal : require('./illegalAnswer.js')  ,
cine : require('./cineAnswer.js')  ,
lol : require('./lolAnswer.js')  ,
emo : require('./emoAnswer.js')  ,
italien : require('./italienAnswer.js')  ,
sandwich : require('./sandwichAnswer.js')  ,
horairesmairie: require('./horairesmairieAnswer.js')  ,
marche: require('./marcheAnswer.js')  ,
fromage: require('./fromageAnswer.js')  ,
visiter: require('./visiterAnswer.js')  ,
brunch: require('./brunchAnswer.js')  ,
sport: require('./sportAnswer.js')  ,
creche: require('./crecheAnswer.js')  ,
spa: require('./spaAnswer.js')  ,
 } 